load(mext);

/* maybe it is not too much work to get this to work under some of these lisps */
if  member(lispname, ["gcl", "ecl", "cmucl", "clisp" ]) then
  print("The maxima package prime_pi does not work under ", lispname,".")
  else (
    require("maxdoc"),
    require("quicklisp"),
    quicklisp_load("cffi"),
    load_in_subdir(["prime_pi","system"]),
    mext_dist_clean(),
    mext_dist_build(),
    mext_dist_user_install(),
    mext_dist_clean());
